stages:
  - build
  - deploy

image: harbor.tilyes.eu/dockerhub_proxy_cache/library/docker:19.03.13

variables:
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: gitlab-runner-gitlab-runner
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE_ALLOWED: gitlab-runner-gitlab-runner

services:
  - docker:19.03.13-dind

build-image:
  stage: build
  image: docker:19.03.12
  script: 
    - |
      for i in $(seq 1 90)
      do
          docker info && break
          echo "Waiting for docker to start"
          sleep 5s
      done
    - mkdir /root/.docker
    - echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json
    - docker info
    - docker pull harbor.tilyes.eu/marthalasz/website:latest || true
    - |
      docker build . \
        -t harbor.tilyes.eu/marthalasz/website:latest \
        --cache-from harbor.tilyes.eu/marthalasz/website:latest
    - docker push harbor.tilyes.eu/marthalasz/website:latest

deploy-website:
  stage: deploy
  image: alpine/k8s:1.16.15
  script:
    - kubectl create job hello --image=busybox -- echo "Hello World" 
